### ISSUE TITLE
Effects Team TODO

### ISSUE THREAD

**Issue by shampson** [nharlow89/ShortSounds#14]
- [x] Function that converts 2 points from EQ to EQ params 
- [x] Function that converts point from Reverb to Reverb params
- [x] OnMove() in UI update the EQ/Reverb params
- [x] Get effects working with playback
- [x] On closing app, update tracks in database, & make sure they are kept
- [x] Code refactoring (on effect clicked, using controller to factor out main activity's possession of logic)

**Comment by Sigotron** [comment]
@shampson has this been taken care of?

**Comment by shampson** [comment]
Yeah a while back.  Closing it
