### ISSUE TITLE
Effects Team: TODO

### ISSUE THREAD

**Issue by shampson** [nharlow89/ShortSounds#2]
For organization purposes (& reference) I wrote up a quick TODO model of what we have
- [x] Onclick track ==> populate track card
  - method for population
    - grab relative layout, replace w/ TrackEffectsPanelFragment
- [x] TrackEffectsPanelFragment
  - UPDATE: Not being used anymore (simply hide/show track editing stuff)
- [x] EffectsListViewAdapter
  - Used to populate effects when a track is clicked
- [x] effectClicked()
  - replace effects list on track w/ EffectFragment
- [x] EffectFragment Interface
  - onCreateView() method:
    - Populates effect view
- [x] Effect View in XML
  - Has key pieces (save & cancel)

After Alpha release:
- [x] Specific effects (Reverb/EQ)
  - Fragments for each

Discuss:
- EffectsListViewAdapter -- What type of adapter is it extending?

**Comment by shampson** [comment]
Last release, finished these pieces
